services:
  https-proxy:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      frontend-estudiantes: { condition: service_started }
      frontend-administracion: { condition: service_started }
      api-gateway: { condition: service_healthy }
    environment:
      PORTAL_HOST: ${DNS_PORTAL_HOST:?DNS_PORTAL_HOST es obligatorio}
      ADMIN_HOST: ${DNS_ADMIN_HOST:?DNS_ADMIN_HOST es obligatorio}
      API_HOST: ${DNS_API_HOST:?DNS_API_HOST es obligatorio}
      API_PORT: ${GATEWAY_PORT:-4600}
    ports: ["443:443"]
    networks: [academia-math]
    volumes:
      - ./docker/nginx-dns.conf:/etc/nginx/templates/default.conf.template:ro
      - ./certificados/academia-matematicas.crt:/etc/nginx/tls/academia.crt:ro
      - ./certificados/academia-matematicas.key:/etc/nginx/tls/academia.key:ro
