map $http_upgrade $connection_upgrade { default upgrade; '' close; }

server {
    listen 443 ssl default_server;
    server_name ${PORTAL_HOST};
    ssl_certificate /etc/nginx/tls/academia.crt;
    ssl_certificate_key /etc/nginx/tls/academia.key;
    client_max_body_size 30m;
    location / {
        proxy_pass http://frontend-estudiantes:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    server_name ${ADMIN_HOST};
    ssl_certificate /etc/nginx/tls/academia.crt;
    ssl_certificate_key /etc/nginx/tls/academia.key;
    client_max_body_size 30m;
    location / {
        proxy_pass http://frontend-administracion:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
